export const firebaseConf = {
  apiKey: "YOUR_API_INFO_HERE",
  authDomain: "YOUR_API_INFO_HERE",
  databaseURL: "YOUR_API_INFO_HERE",
  projectId: "YOUR_API_INFO_HERE",
  storageBucket: "YOUR_API_INFO_HERE",
  messagingSenderId: "YOUR_API_INFO_HERE"
}

export const firebaseIllus = {
  auth: require('../assets/img/auth.png'),
  auth_google: require('../assets/img/auth_google.png'),
  cloud_functions: require('../assets/img/cloud_functions.png'),
  cloud_functions_deploy: require('../assets/img/cloud_functions_deploy.png'),
  cloud_storage: require('../assets/img/cloud_storage.png'),
  cloud_storage_connectivity: require('../assets/img/cloud_storage_connectivity.png'),
  cloud_storage_roles: require('../assets/img/cloud_storage_roles.png'),
  crash: require('../assets/img/crash.png'),
  crash_bad_ratings: require('../assets/img/crash_bad_ratings.png'),
  database: require('../assets/img/database.png'),
  database_security: require('../assets/img/database_security.png'),
  deep_link: require('../assets/img/deep_link.png'),
  deep_link_send_to_phone: require('../assets/img/deep_link_send_to_phone.png'),
  google_analytics: require('../assets/img/google_analytics.png'),
  google_analytics_segmetns: require('../assets/img/google_analytics_segmetns.png'),
  hosting_deploy: require('../assets/img/hosting_deploy.png'),
  hosting_free_ssl: require('../assets/img/hosting_free_ssl.png'),
  hosting_ssd: require('../assets/img/hosting_ssd.png'),
  perf_graphs: require('../assets/img/perf_graphs.png'),
  perfs_connectivity: require('../assets/img/perfs_connectivity.png'),
  perfs_stats: require('../assets/img/pers_stats.png'),
  push_prog: require('../assets/img/push_prog.png'),
  push_targetings: require('../assets/img/push_targetings.png'),
  qr_code: require('../assets/img/qr_code.png'),
  remote_config: require('../assets/img/remote_config.png'),
  test_lab: require('../assets/img/test_lab.png'),
  test_lab_report: require('../assets/img/test_lab_report.png'),
  test_lab_robot: require('../assets/img/test_lab_robot.png'),
  all_funcs: require('../assets/img/all_funcs.png'),
  natives: require('../assets/img/natives.png'),
  ekino: require('../assets/img/ekino.png'),
}
